cmake_minimum_required(VERSION 3.18)
project(XPGraph LANGUAGES CXX CUDA)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CUDA_STANDARD 20)
set(CMAKE_CUDA_SEPARABLE_COMPILATION ON)
set(CMAKE_CUDA_ARCHITECTURES native)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

set(BUILD_CPP_BINDINGS ON CACHE BOOL "")
set(BUILD_TESTING OFF CACHE BOOL "")
set(BUILD_TESTING_INTEGRATION OFF CACHE BOOL "")
add_subdirectory(thirdparty/mgclient EXCLUDE_FROM_ALL)
set_target_properties(mgclient-static PROPERTIES POSITION_INDEPENDENT_CODE ON)

include_directories(include thirdparty ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
add_subdirectory(src)
add_subdirectory(benchmarks)
add_subdirectory(tests)
